name: Oracle Cloud Free Tier Hunter

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Setup OCI Credentials
        run: |
          # 1. Tạo file Private Key bí mật
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > oci_api_private_key.pem
          chmod 600 oci_api_private_key.pem
          
          # 2. Tạo đúng file oci_config mà hệ thống đang đòi
          echo "[DEFAULT]" > oci_config
          echo "user=${{ secrets.OCI_USER_OCID }}" >> oci_config
          echo "fingerprint=${{ secrets.OCI_FINGERPRINT }}" >> oci_config
          echo "tenancy=${{ secrets.OCI_TENANCY_OCID }}" >> oci_config
          echo "region=${{ secrets.OCI_REGION }}" >> oci_config
          echo "key_file=$(pwd)/oci_api_private_key.pem" >> oci_config

      - name: Run Hunter Bot
        run: |
          python main.py
