name: Oracle Cloud Free Tier Hunter

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Setup OCI Credentials & Fake SSH File
        run: |
          # 1. Tạo file Private Key đăng nhập API
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > oci_api_private_key.pem
          chmod 600 oci_api_private_key.pem
          
          # 2. Tạo file oci_config vật lý
          echo "[DEFAULT]" > oci_config
          echo "user=${{ secrets.OCI_USER_OCID }}" >> oci_config
          echo "fingerprint=${{ secrets.OCI_FINGERPRINT }}" >> oci_config
          echo "tenancy=${{ secrets.OCI_TENANCY_OCID }}" >> oci_config
          echo "region=${{ secrets.OCI_REGION }}" >> oci_config
          echo "key_file=$(pwd)/oci_api_private_key.pem" >> oci_config

          # 3. Tạo file SSH ảo (id_rsa.pub) để vượt qua bước check của Bot
          echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC fake-key-for-bot-bypass" > id_rsa.pub

      - name: Run Hunter Bot
        run: |
          python main.py
